return {
	voidstalker_ghost = {
		acceleration = 0.1105,
		brakerate = 100,
		buildcostenergy = 1250,
		buildcostmetal = 85,
		buildpic = "ARMSH.DDS",
		buildtime = 1700,
		cancloak = true,
		canmove = true,
		category = "BOT MOBILE WEAPON ALL NOTSUB NOTSHIP NOTAIR NOTHOVER SURFACE EMPABLE",
		collisionvolumeoffsets = "0 1 0",
		collisionvolumescales = "24 12 26",
		collisionvolumetype = "CylY",
		explodeas = "",
		--explodeas = "smallExplosionGeneric",
		footprintx = 3,
		footprintz = 3,
		idleautoheal = 5,
		idletime = 1800,
		initcloaked = true,
		maxdamage = 200,
		maxslope = 16,
		maxvelocity = 3.79,
		maxwaterdepth = 0,
		movementclass = "BOT2",
		mincloakdistance = 300,
		nochasecategory = "VTOL",
		objectname = "Voidstalkers/voidstalker_ghost.s3o",
		script = "Voidstalkers/voidstalker_ghost.lua",
		seismicsignature = 1,
		selfdestructas = "smallExplosionGenericSelfd",
		sightdistance = 550,
		stealth = true,
		turninplace = true,
		turninplaceanglelimit = 90,
		turninplacespeedlimit = 2.9634,
		turnrate = 640,
		customparams = {
			nohealthbars = true,
			model_author = "bob",
			
		},
		weapondefs = {
			-- melee = {
				--areaofeffect = 0,
				--craterareaofeffect = 0,
				--craterboost = 0,
				--cratermult = 0,
				--edgeeffectiveness = 0.15,
				--explosiongenerator = "",
				--firesubmersed = false,
				--impulseboost = 0,
				--impulsefactor = 0,
				--name = "Crawlingbomb Dummy Weapon",
				--range = 64,
				--reloadtime = 1,
				--soundhitwet = "",
				--soundhitwetvolume = 0,
				--tolerance = 1000000,
				--weapontype = "Melee",
				--weaponvelocity = 100000,
				--damage = {
				--	default = 25,
				--},
			 -- },	
			darkness = {
				areaofeffect = 8,
				avoidfeature = false,
				burst = 1,
				burstrate = 0.1,
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				cylindertargeting = 1,
				edgeeffectiveness = 0.15,
				explosiongenerator = "custom:plasmahit-small",
				firestarter = 100,
				impulseboost = 0.123,
				impulsefactor = 0.123,
				intensity = 0.7,
				name = "Rapid-fire close-quarters g2g plasma guns",
				noselfdamage = true,
				range = 200,
				reloadtime = 1,
				rgbcolor = "0 0 0",
				size = 4,
				soundhitwet = "splshbig",
				soundstart = "flashemg",
				sprayangle = 1180,
				tolerance = 5000,
				turret = true,
				weapontimer = 0.1,
				weapontype = "Cannon",
				weaponvelocity = 250,
				customparams = {
					expl_light_mult = 0.8,
					expl_light_radius_mult = 0.85,
					light_mult = 0.8,
					light_radius_mult = 0.85,
				},
				damage = {
					bombers = 10,
					default = 30,
					fighters = 10,
					vtol = 10,
				},
			},
		},
		weapons = {
			[1] = {
				def = "DARKNESS",
			},
			--[1] = {
			--	def = "MELEE",
			--},

		},
	},
}
