return {
	voidstalker_ghast = {
		acceleration = 0.1105,
		brakerate = 0.1105,
		buildcostenergy = 1250,
		buildcostmetal = 85,
		buildpic = "ARMSH.DDS",
		buildtime = 1700,
		cancloak = true,
		canmove = true,
		category = "BOT MOBILE WEAPON ALL NOTSUB NOTSHIP NOTAIR NOTHOVER SURFACE EMPABLE",
		collisionvolumeoffsets = "0 1 0",
		collisionvolumescales = "24 12 26",
		collisionvolumetype = "CylY",
		explodeas = "smallExplosionGeneric",
		footprintx = 3,
		footprintz = 3,
		idleautoheal = 5,
		idletime = 1800,
		initcloaked = true,
		maxdamage = 10000,
		maxslope = 16,
		maxvelocity = 3.79,
		maxwaterdepth = 0,
		movementclass = "BOT2",
		mincloakdistance = 150,
		nochasecategory = "VTOL",
		objectname = "Voidstalkers/voidstalker_ghast.s3o",
		script = "Voidstalkers/voidstalker_ghast.lua",
		seismicsignature = 1,
		selfdestructas = "smallExplosionGenericSelfd",
		sightdistance = 550,
		stealth = true,
		turninplace = true,
		turninplaceanglelimit = 90,
		turninplacespeedlimit = 2.9634,
		turnrate = 640,
		customparams = {
			nohealthbars = true,
			model_author = "bob",
			
		},
	},
}
