return {
	voidstalker_voidcrystal_level_1 = {
		acceleration = 0,
		brakerate = 0,
		buildangle = 4096,
		buildcostenergy = 69000,
		buildcostmetal = 9700,
		buildpic = "ARMAFUS.DDS",
		buildtime = 312498,
		canrepeat = false,
		capturable = false,
		category = "ALL NOTSUB NOWEAPON NOTAIR NOTHOVER SURFACE EMPABLE",
		collisionvolumeoffsets = "0 0 0",
		collisionvolumescales = "20 20 20",
		collisionvolumetype = "Box",
		damagemodifier = 0.95,
		energymake = 3000,
		energystorage = 9000,
		explodeas = "",
		footprintx = 2,
		footprintz = 2,
		icontype = "building",
		idleautoheal = 5,
		idletime = 1800,
		maxdamage = 7150,
		maxslope = 13,
		maxwaterdepth = 0,
		objectname = "Voidstalkers/voidstalker_voidcrystal_level_1.s3o",
		reclaimable = false,
		script = "Voidstalkers/voidstalker_voidcrystal.lua",
		seismicsignature = 0,
		selfdestructas = "",
		sightdistance = 273,
		yardmap = "oooo",
		customparams = {
			crystal_level = 1,
		},
		sfxtypes = {
			pieceexplosiongenerators = {
				[1] = "deathceg2",
				[2] = "deathceg3",
				[3] = "deathceg4",
			},
		},
		sounds = {
			canceldestruct = "cancel2",
			underattack = "warning1",
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			select = {
				[1] = "fusion1",
			},
		},
	},
}
