return {
	voidstalker_com_archon = {
		acceleration = 0.2,
		blocking = false,
		brakerate = 0.2,
		builder = true,
		buildcostenergy = 1250,
		buildcostmetal = 85,
		builddistance = 40,
		buildpic = "ARMSH.DDS",
		buildtime = 1700,
		canrepair = true,
		canfly = true,
		canmove = true,
		category = "ALL WEAPON NOTSUB VTOL NOTHOVER",
		collide = false,
		cruisealt = 40,
		collisionvolumeoffsets = "0 1 0",
		collisionvolumescales = "24 12 26",
		collisionvolumetype = "CylY",
		energymake = 100000,
		energystorage = 10000000,
		explodeas = "",
		--explodeas = "smallExplosionGeneric",
		footprintx = 3,
		footprintz = 3,
		holdsteady = true,
		hoverattack = true,
		idleautoheal = 5,
		idletime = 1800,
		mass = 500000,
		maxdamage = 200000,
		maxslope = 16,
		maxvelocity = 4,
		maxwaterdepth = 0,
		metalmake = 1000,
		metalstorage = 10000000,
		mincloakdistance = 300,
		nochasecategory = "VTOL",
		objectname = "Voidstalkers/voidstalker_com_archon.s3o",
		releaseheld  = true,
		repairspeed = 3000,
		script = "Voidstalkers/voidstalker_com_archon.lua",
		seismicsignature = 0,
		selfdestructas = "smallExplosionGenericSelfd",
		sightdistance = 100,
		stealth = true,
		turninplace = true,
		turninplaceanglelimit = 90,
		turninplacespeedlimit = 2.9634,
		turnrate = 640,
		workertime = 500000,
		buildoptions = {
			[1] = "armsolar"
		},
		customparams = {
			nohealthbars = true,
			model_author = "bob",
			
		},
		weapondefs = {
			-- melee = {
				--areaofeffect = 0,
				--craterareaofeffect = 0,
				--craterboost = 0,
				--cratermult = 0,
				--edgeeffectiveness = 0.15,
				--explosiongenerator = "",
				--firesubmersed = false,
				--impulseboost = 0,
				--impulsefactor = 0,
				--name = "Crawlingbomb Dummy Weapon",
				--range = 64,
				--reloadtime = 1,
				--soundhitwet = "",
				--soundhitwetvolume = 0,
				--tolerance = 1000000,
				--weapontype = "Melee",
				--weaponvelocity = 100000,
				--damage = {
				--	default = 25,
				--},
			 -- },	
			lightness = {
				accuracy = 20,
				areaofeffect = 16,
				avoidfeature = false,
				burst = 6,
				burstrate = 0.0675,
				burnblow = false,
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				duration = 0.038,
				edgeeffectiveness = 0.85,
				explosiongenerator = "custom:plasmahit-sparkonly",
				fallOffRate = 0.2,
				firestarter = 0,
				impulseboost = 0.4,
				impulsefactor = 1.5,
				intensity = 0.8,
				name = "Rapid-fire a2g machine guns",
				noselfdamage = true,
				ownerExpAccWeight = 4.0,
				proximitypriority = 3,
				range = 500,
				reloadtime = 0.4,
				smoketrail = true,
				rgbcolor = "1 0.95 0.4",
				size = 2.25,
				soundhit = "bimpact3",
				soundhitwet = "splshbig",
				soundstart = "minigun3",
				soundstartvolume = 4.5,
				sprayangle = 600,
				thickness = 1.1,
				tolerance = 6000,
				turret = true,
				--weapontimer = 1,
				weapontype = "LaserCannon",
				weaponvelocity = 950,
				customparams = {
					light_color = "1 0.9 0.15",
					light_radius_mult = 0.5,
					light_mult = 1.7,
					expl_light_life_mult = 0.1,
					expl_light_radius_mult = 0.01,
					expl_light_mult = 0.01,
					expl_light_color = "0.45 0.40 0.35",
				},
				damage = {
					bombers = 21,
					commanders = 5,
					default = 21,
					fighters = 21,
					vtol = 21,
				},
			},
		},
		weapons = {
			[1] = {
				def = "LIGHTNESS",
			},
			--[1] = {
			--	def = "MELEE",
			--},

		},
	},
}
