return {
	voidstalker_tesseract = {
		acceleration = 0,
		brakerate = 4.5,
		buildcostenergy = 3200,
		buildcostmetal = 210,
		builddistance = 400,
		builder = true,
		buildpic = "ARMNANOTC.DDS",
		buildtime = 5312,
		canassist = true,
		canfight = true,
		canguard = true,
		canpatrol = true,
		canreclaim = true,
		canrepeat = false,
		canstop = true,
		cantbetransported = false,
		category = "ALL NOTSUB NOWEAPON NOTAIR NOTHOVER SURFACE EMPABLE",
		collisionvolumeoffsets = "0 0 0",
		collisionvolumescales = "31 32 31",
		collisionvolumetype = "CylY",
		energyuse = 30,
		explodeas = "nanoboom",
		footprintx = 11,
		footprintz = 11,
		icontype = "building",
		idleautoheal = 5,
		idletime = 1800,
		mass = 700,
		maxdamage = 100000,
		maxslope = 10,
		maxwaterdepth = 0,
		movementclass = "NANO",
		objectname = "Voidstalkers/voidstalker_tesseract.s3o",
		script = "Voidstalkers/voidstalker_tesseract.lua",
		seismicsignature = 0,
		selfdestructas = "nanoselfd",
		sightdistance = 380,
		terraformspeed = 1000,
		turnrate = 1,
		upright = true,
		workertime = 200,
		yardmap = "ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo",
		customparams = {
			nohealthbars = true,
			model_author = "bob",
			iscommander = true,
			
		},
		
	},
}
