return {
	voidstalker_warpring = {
		acceleration = 0.015,
		activatewhenbuilt = true,
		bankingallowed = false,
		brakerate = 0.05,
		buildangle = 16384,
		buildcostenergy = 250000,
		buildcostmetal = 25000,
		buildpic = "armfepocht4.DDS",
		buildtime = 250000,
		canfly = true,
		canmove = true,
		category = "ALL WEAPON NOTSUB VTOL NOTHOVER T4AIR",
		collide = true,
		collisionvolumeoffsets = "0 -14 10",
		collisionvolumescales = "70 70 170",
		collisionvolumetype = "CylZ",
		corpse = "DEAD",
		cruisealt = 100,
		explodeas = "flagshipExplosion",
		footprintx = 6,
		footprintz = 6,
		hoverattack = true,
		icontype = "air",
		idleautoheal = 25,
		idletime = 1800,
		losemitheight = 52,
		mass = 1000000,
		maxdamage = 60000,
		maxvelocity = 0.6,
		maxwaterdepth = 15,
		nochasecategory = "VTOL",
		objectname = "Voidstalkers/voidstalker_warpring.s3o",
		script = "Voidstalkers/voidstalker_warpring.lua",
		radardistance = 1530,
		radaremitheight = 52,
		seismicsignature = 0,
		selfdestructas = "flagshipExplosionSelfd",
		sightdistance = 689,
		turninplace = true,
		turninplaceanglelimit = 90,
		turnrate = 135,
		upright = true,
		customparams = {
			
			paralyzemultiplier = 0,
			
		},
		
	},
}
